// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package internal

import (
	"main/internal/biz"

	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitDemoService(db *gorm.DB) *DemoService {
	demoBiz := biz.NewDemoBiz(db)
	demoService := NewDemoService(demoBiz)
	return demoService
}
